# setup environment
dist: bionic
language: go

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-hcl"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

matrix:
  include:
  - os: linux
  - os: linux
    env: ATOM_CHANNEL=beta

# execute tests
install:
  - https://releases.hashicorp.com/vault/1.3.4/vault_1.3.4_linux_amd64.zip
  - sudo unzip vault_1.3.4_linux_amd64.zip -d /usr/bin/
before_script: vault version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
