# setup environment
dist: jammy
language: go

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
  - APM_TEST_PACKAGES='language-hcl'
  - ATOM_LINT_WITH_BUNDLED_NODE='true'
  - VERSION='1.8.9'

os: linux

# execute tests
install:
  - sudo wget "https://releases.hashicorp.com/vault/${VERSION}/vault_${VERSION}_linux_amd64.zip"
  - sudo unzip "vault_${VERSION}_linux_amd64.zip" -d /usr/bin/
before_script: vault version
script: 'curl -s https://raw.githubusercontent.com/mschuchard/vagrant-boxes-docker-images/master/atom-build-package.sh | sh'
